import type { Metadata } from "next";

import "./globals.css";
import Header from "./components/header";
import { Sidebar } from "./components/admin-sidebar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    < >
<Header/>
<Sidebar/>
      <div className="min-h-full flex flex-col">{children}</div>
    </>
  );
}
